name: Build Development Environment

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/base

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Debug SSH Public Key
      run: |
        echo "SSH_PUBLIC_KEY (first 50 chars): $(echo '${{ secrets.SSH_PUBLIC_KEY }}' | cut -c1-50)..."
        echo "SSH_PUBLIC_KEY (last 50 chars): ...$(echo '${{ secrets.SSH_PUBLIC_KEY }}' | tail -c50)"
        echo "SSH_PUBLIC_KEY length: $(echo '${{ secrets.SSH_PUBLIC_KEY }}' | wc -c)"

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          SSH_PUBLIC_KEY=${{ secrets.SSH_PUBLIC_KEY }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        no-cache: true

    - name: Print image info
      run: |
        echo "Image built and pushed successfully!"
        echo "Image tags: ${{ steps.meta.outputs.tags }}"
        echo ""
        echo "To run the container with SSH access:"
        echo "docker run -d -p 2222:22 --name dev-env ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
        echo ""
        echo "To connect via SSH:"
        echo "ssh -p 2222 root@localhost"
